spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5432/fade
spring.datasource.username=postgres
spring.datasource.password=test@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
